### ISSUE TITLE
Stockage de mots de passes.

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/afpy_gestion#4]
Que doit-on stocker et se partager :

- logins et mots de passe de différents comptes
    - twitter
    - mastodon
    - banque
    - quoi d'autre ?
- Documents ?

Essais :
 - On a utilisé passbolt pendant environ un an avec [quelques soucis](https://github.com/AFPy/afpy_gestion/issues/4#issuecomment-564977458).

**Comment by Seluj78** [comment]
Alors je connais pas le format `kbdx`, a voir :)

Sinon j'ai déja utilisé et mis en place passbolt (https://www.passbolt.com/) et c'est top !

**Comment by JulienPalard** [comment]
Je pense que le `kbdx` est bien quand on est tout seul, c'est un format binaire (du chiffré quoi) donc ça se comporte mal face a un conflit (pas simple a merger).

Passbolt est open-source, je plussoie de tenter d'en installer un sur l'infra de l'afpy via ansible. On peut débloquer le budget pour une petite machine pour ça ?

**Comment by Seluj78** [comment]
O/ bonsoir a tous !

Comme j'en avait discuté avec Julien je suis chaud pour tester passbolt

**Comment by JulienPalard** [comment]
https://passbolt.afpy.org en test.
Attention les backups sont pas en place, c'est du test.
Le playbook ansible est pas super mature non plus (https://github.com/AFPy/infra/blob/master/playbook.yml#L40, https://github.com/laxathom/ansible-role-passbolt/issues)

@Seluj78 et @JulienPalard sont admin dessus, n'hésitez pas a nous demander des comptes.

**Comment by JulienPalard** [comment]
J'ai crée le compte Mastodon sur l'instance mamot.fr, le mot de passe est dans le passbolt.

**Comment by JulienPalard** [comment]
# Passbolt

Environ un an de test de passbolt, je vote pour arrêter :

- Je n'y ai plus accès a cause d'un bug du plugin de navigateur
- Le plugin est obligatoire (et j'aime pas les plugins)
- Le role ansible pour l'installer malgré [qq contribs](https://github.com/laxathom/ansible-role-passbolt/pulls?q=is%3Apr+is%3Aclosed) n'est toujours pas fonctionnel, passbolt est galère à installer.
- On ne prend pas le temps de faire les mises à jour vu qu'on a pas ansible pour nous le faire, niveau sécu c'est pas très bien.

# Discusson avec Michael sur IRC
- Tout ce qui est basé sur git risque de freiner certaines personnes (quelqu'un qui veut faire de la com' pour l'AFPy mais qui n'est pas technique)
- en l'occurence, des trucs pour gerer les mots de passes partagés, y a tout qui daube :/

misc a raison sur une queston : avant de trouver comment résoudre le problème, il faudrait le définir : on a combien de mots de passe a se partager a combien ? Mis à jours tous les combien de temps ? Sur des services de quel "sensibilité" ? Y'a twitter, mastodon, quoi d'autre ? La banque ?

# Proposition de Julien

> Un fichier `.kdbx` sur ce repo, chiffré avec un mot de passe qu'on peut tous retenir, et un keyfile qu'on se partage hors ligne. Vu qu'on ne l'édite pas souvent on aura pas de conflits, et les conflits se règlent pas trop trop mal avec `keepassxc-cli merge` (mais pas avec git vu que le fichier est chiffré). Si quelqu'un veut y accéder sans avoir git on peut lui donner un lien direct vers le fichier, ou on peut simplement lui donner le ou les mots de passes dont il a besoin.

**Comment by mscherer** [comment]
En fait, comme Julien m'a demandé de détailler un peu plus notre discussion, je me permet d'intervenir. Mon expérience, c'est que commencer par lister les solutions sans poser les problèmes à résoudre, ça donne souvent des soucis sur le long terme (mais que tout le monde, à mon grand regret, fait ça)

Du coup, oui, pour ce cas la, je pense qu'il faut déjà se poser la question de la liste des mots de passe existants et futurs, et surtout, il se passe quoi dans 2 cas:
* quelqu'un qui n'a pas accès se retrouve à avoir accès (mot de passe réutilisé, personne viré, etc)
* quelqu'un qui doit avoir accès n'a pas accès, avec le cas particulier de plus personne n'a accès.

De mon expérience  avec des communautés du libre et en entreprise, le 2eme cas est beaucoup plus courant que le 1er. Genre, j'ai quasiment jamais vu de conséquences négatives du premier en pratique (même si ça existe, voir l'exemple de Capital One y a pas longtemps), alors que le second arrive quand même grosso modo 1 fois par an autour de moi. Je suppose que c'est surtout ce cas qui cherche à être résolu par le partage de mot de passe (et donc le stockage implicite).

La gestion des mots de passe (partagé ou pas), c'est chiant, donc le premier point que j'ai en tête, c'est d'en avoir le moins possible. Par exemple, le mot de passe d'une base de données, il n'y a pas besoin de le connaitre ou de le noter. L'appli qui l'utilise doit l'avoir, et ça doit être synchro avec le compte de la DB, mais c'est tout. 

Quelqu'un doit modifier la base va avoir soit une procédure pour changer ça, soit sait ou aller le retrouver. Idéalement aussi, le fait d'avoir le mot de passe publié devrait pas avoir d'impact (pour l'exemple d'une BD, avoir un firewall qui filtre par IP aide à réduire les problèmes).

Le point sur git, j'ai des anecdotes mais j'ai déjà vu la combo la moins ergonomique du monde: vim + git + gpg, le tout lié par un plugin vim. Point bonus sur gpg qui s'étouffe sur le nom d'un des membres de l'équipe (qui vient donc de sa clé GPG), ce qui fait qu'il a perdu souvent son accès (et qu'il a vu ça au mauvais moment, genre quand il est d'astreinte).

Du coup, un autre point,  c'est que comme tout les mots de passes ne sont pas égaux, et que tout les utilisateurs n'ont pas forcément la même envie de masochisme (lire "utiliser git, gpg et vim"), il faut sans doute séparer les mots de passe en différentes classes, et pour ça, se poser des questions sur leur différences, notamment en cas de perte, de fuite ou autre.

Prenons l'exemple de Twitter. Avec un usage normal (cad si le compte twitter est pas lié à autre chose), le pire qui arrive, c'est quelqu'un qui va poster un truc obscène comme "Je trouve que la gestion des chaines de python 2 était vraiment exemplaire". On va le voir, on va remettre le mot de passe à zero, et voila. Donc est ce qu'il y a besoin de sortir la grosse artillerie pour éviter ça, je doute. Par contre, savoir comment on remets le mot de passe à 0, savoir qui a mis son email, etc, c'est des choses à vérifier, et c'est pas le stockage des mots de passe qui va changer ça.

Savoir qu'on peut le changer facilement (et en fait, le faire régulièrement pour voir si rien n'a changé), et idéalement, envoyer le lien de reset à tout les gens censé avoir un accés me parait plus sain. 

Du coup, oui, sans vouloir dire quoi faire (sans le faire), je pense qu'une liste serait utile. Ensuite, pour chaque mot de passe de la liste se demander:
* qui a accès maintenant (avec quel outils, quel usage, quel familiarité)
* qui peut avoir accès plus tard (supposer de connaitre l'admin sys pour le mot de passe root, ok, pour la banque, pas trop)
* est ce qu'on doit savoir qui a utilisé le mot de passe (pour l'AFPY, sans doute que non)
* il se passe quoi si on perds le mot de passe (exemple, changement sans être mis à jour), est ce qu'on peut le voir facilement, ou on va le voir dans l'urgence. Je dit pas de mettre du monitoring dessus, mais techniquement, c'est faisable bien qu'overkill.
* est ce que ça importe d'avoir les anciennes versions du mot de passe, si oui, combien de temps, pourquoi
* il se passe quoi si le mot de passe arrive la ou il faut pas
* est ce qu'un mot de passe partagé va pas contre l'idée de 2FA, et si oui, qu'est ce qu'on choisit entre les 2 ?

Une fois qu'il y a la réponse pour chaque mot de passe, la, on peut commencer à grouper et mettre des contraintes et proposer des solutions sur la base des contraintes. Je précise des solutions, parce que par exemple, s'envoyer le mot de passe twitter par signal et effacer le message me parait suffisant. Ça me parait overkill de le stocker de façon super sécurisé sur un serveur ultraprotegé si il est en clair sur les téléphones de 3 personnes avec un android pas à jour, par exemple.

À contrario, les histoires de banque, c'est un chouia plus sensible, mais pareil, vu les montants, faut pas se dire qu'il va y avoir une équipe de 10 personnes pendant 6 mois comme sur les attaques sur les trucs de crypto monnaie.

Et si les gens doivent rajouter un mot de passe dans la liste, je pense qu'il faut prendre l'habitude de  repasser par la liste de questions, et regarder si les solutions font l'affaire ou pas.

**Comment by JulienPalard** [comment]
Tiens, cette issue est toujours ouverte ? Damned.

On utilise https://github.com/AFPy/pass/ depuis la migration hors de passbolt, ça semble faire consensus.
